#DELETE http://localhost:3000/api/pessoa/deletar?email=luannf@gmail.com
#GET http://localhost:3000/api/pessoa
#POST http://localhost:3000/api/pessoa/criar
#PUT http://localhost:3000/api/pessoa/editar?email=luannf@gmail.com&nome=luan
