version: "3.9"
services:
  web:
    build: .
    command: "npm run dev"
    container_name: ExTags
    depends_on:
      - postgres-compose
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app/
    working_dir: /usr/src/app/
  postgres-compose:
    container_name: postgres
    image: postgres:12.4-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: "ExTags"
      POSTGRES_PASSWORD: "1345"
      PGDATA: /var/lib/postgresql/data/pgdata
      LANG: pt_BR.utf8
    ports:
      - "5440:5432"

  pgadmin-compose:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: example@example.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin1234
    ports:
      - "15432:80"
    depends_on:
      - postgres-compose

networks:
  network:
    driver: bridge

volumes:
  postgres-data:
    external: true